name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/940497197574/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@playground-jamespain-poc-21017.iam.gserviceaccount.com'
          create_credentials_file: true
          export_environment_variables: true
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: playground-jamespain-poc-21017

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          # Get short SHA for the image tag
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          
          # Configure Docker to use gcloud credentials
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          
          # Build and push the Docker image
          docker build \
            -t europe-west2-docker.pkg.dev/playground-jamespain-poc-21017/awards/awards:${SHORT_SHA} \
            -t europe-west2-docker.pkg.dev/playground-jamespain-poc-21017/awards/awards:latest \
            .
          docker push europe-west2-docker.pkg.dev/playground-jamespain-poc-21017/awards/awards:${SHORT_SHA}
          docker push europe-west2-docker.pkg.dev/playground-jamespain-poc-21017/awards/awards:latest

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          # Get short SHA for the image tag
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          
          # Deploy to Cloud Run with OpenAI API key from GitHub secrets
          gcloud run deploy awards \
            --image europe-west2-docker.pkg.dev/playground-jamespain-poc-21017/awards/awards:${SHORT_SHA} \
            --region europe-west2 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"

      - name: Set IAM policy for public access
        run: |
          gcloud run services add-iam-policy-binding awards \
            --region=europe-west2 \
            --member=allUsers \
            --role=roles/run.invoker

      - name: Get deployment URL
        id: deployment-url
        run: |
          URL=$(gcloud run services describe awards --region europe-west2 --format='value(status.url)')
          echo "Deployed to: ${URL}"
